name: Build and deploy docs to GitHub Pages

on:
  - push
  - pull_request
  # Allow running this workflow manually from the Actions tab
  - workflow_dispatch

# Set permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write  # to verify the deployment originates from an appropriate source

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}  # For Conda activation scripts to work correctly
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: pip install astra-toolbox sphinx sphinx-rtd-theme sphinx-tabs
    - name: Build docs
      run: 'make html'
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '_build/html/'
    - name: Deploy to GitHub pages
      id: deployment
      if: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request' }}
      uses: actions/deploy-pages@v4
